name: lab_2_moviles
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.3
  flutter_staggered_animations: ^1.1.0
  flutter_spinkit: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
